FROM node:16.13.2-alpine

WORKDIR /var/backend

COPY package.json .

RUN npm install --prefer-offline --no-audit --progress=false

COPY . .

RUN mkdir dist && mkdir uploads

CMD [ "npm", "run", "start:watch" ]
